services:

  Profile.TypeOrmConfig:
    class: ../../../../../contexts/profile/shared/infrastructure/persistence/postgre/TypeOrmConfigFactory
    method: 'createConfig'

  Profile.user.application.UserCreator:
    class: ../../../../../contexts/profile/user/application/UserCreator
    arguments: ["@Profile.user.domain.UserRepository"]

  Profile.user.domain.UserRepository:
    class: ../../../../../contexts/profile/user/infrastructure/persistence/FileUserRepository
    arguments: [""]
