services:
  Profile.TypeOrmConfig:
    factory:
      class: ../../../../../contexts/profile/shared/infrastructure/persistence/postgre/TypeOrmConfigFactory
      method: 'createConfig'

  Profile.ConnectionManager:
    factory:
      class: ../../../../../contexts/shared/infrastructure/persistence/typeorm/TypeOrmClientFactory
      method: 'createClient'
    arguments: [ 'profile', '@Profile.TypeOrmConfig' ]

  Profile.hostedOnboarding.domain.HostedOnboardingRepository:
    class: ../../../../../contexts/profile/hosted-onboarding/infrastructure/persistence/TypeOrmHostedOnboardingRepository
    arguments: [ "@Profile.ConnectionManager" ]

  Profile.hostedOnboarding.application.HostedOnboardingCreator:
    class: ../../../../../contexts/profile/hosted-onboarding/application/HostedOnboardingCreator
    arguments: [ "@Profile.hostedOnboarding.domain.HostedOnboardingRepository" ]

  Profile.hostedOnboarding.application.HostedOnboardingFinder:
    class: ../../../../../contexts/profile/hosted-onboarding/application/HostedOnboardingFinder
    arguments: [ "@Profile.hostedOnboarding.domain.HostedOnboardingRepository" ]

  Profile.hostedOnboarding.application.HostedOnboardingUpdater:
    class: ../../../../../contexts/profile/hosted-onboarding/application/HostedOnboardingUpdater
    arguments: [ "@Profile.hostedOnboarding.domain.HostedOnboardingRepository" ]
