services:

  Apps.profile.controllers.StatusGetController:
    class: ../../rest/controllers/StatusGetController
    arguments: []

  Apps.profile.controllers.UserPutController:
    class: ../../rest/controllers/UserPutController
    arguments: ["@Profile.user.application.UserCreator"]

  UserResolver:
    class: ../../graphql/resolvers/UserResolver
    arguments: ["@Profile.user.application.UserCreator", "@Profile.user.application.UserFinder", "@Profile.user.application.UsersFinder", "@Profile.user.application.UserUpdater", "@Profile.hostedOnboarding.application.HostedOnboardingFinder"]

  HostedOnboardingResolver:
    class: ../../graphql/resolvers/HostedOnboardingResolver
    arguments: ["@Profile.hostedOnboarding.application.HostedOnboardingCreator", "@Profile.user.application.UserFinder", "@Profile.hostedOnboarding.application.HostedOnboardingFinder", "@Profile.hostedOnboarding.application.HostedOnboardingUpdater"]
