services:

  Apps.profile.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.profile.controllers.UserPutController:
    class: ../../controllers/UserPutController
    arguments: ["@Profile.user.application.UserCreator"]
